version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: applicationstop.sh
      timeout: 10
  AfterInstall:
    - location: aftetinstall.sh
      timeout: 10
