version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  AfterInstall:
    - location: aftetinstall.sh
      timeout: 10
  ApplicationStop:
    - location: applicationstop.sh
      timeout: 10
